### ISSUE TITLE
after updating geoip database, how to reopen it

### ISSUE THREAD

**Issue by dbsdsun** [fgsch/libvmod-geoip2#12]
The geoip database is updated periodically.

How to reopen it, after updating? 
What I can think is restart varnish, that seems a bit awkward.
Thanks,
Wilson

**Comment by fgsch** [comment]
You could use vcl_reload to reload the VCL or just `service varnish reload`.
That'd use the updated file.

**Comment by dbsdsun** [comment]
excuse me, is vcl_reload a vcl built-in function? I couldn't find it.
And what I want to reload is in-line vcl
Thanks,

**Comment by fgsch** [comment]
There is no builtin vcl reload.  You have to use either the script `varnish_reload_vcl` (sorry, got the name wrong earlier) or `service varnish reload`.

Alternatively you can implement your own reload based on what the script does. See https://github.com/varnishcache/pkg-varnish-cache/blob/master/redhat/varnish_reload_vcl.

**Comment by dugwood** [comment]
I have the same concern, knowing that the Maxmind database is updated at most once a week.

I've run some tests, and it seems the child isn't restarted upon a certain number of requests, so you can't count on that (for example it would restart some time after the database is updated).

I've added: `std.syslog(9, "reloaded country!");` right after geoip2 init (in vcl_init), and I can confirm the behaviour: `service varnish reload` will reload the database, as seen in syslog (child PID is 14957):
```
systemd[1]: Reloading Varnish HTTP accelerator.
varnishd[9899]: CLI telnet ::1 43639 ::1 6082 Rd auth c2125a3c666830c95628dd4f9d455f436d9ef6c4a35a7e2e307744ead048a377
varnishd[9899]: CLI telnet ::1 43639 ::1 6082 Wr 200 -----------------------------#012Varnish Cache CLI 1.0#012-----------------------------#012Linux,3.16.0-4-amd64,x86_64,-junix,-smalloc,-smalloc,-hcritbit#012varnish-5.1.3 revision 05c5ac6b9#012#012Type 'help' for command list.#012Type 'quit' to close CLI session.
varnishd[9899]: CLI telnet ::1 43639 ::1 6082 Rd ping
varnishd[9899]: CLI telnet ::1 43639 ::1 6082 Wr 200 PONG 1504722403 1.0
varnishd[9899]: CLI telnet ::1 43639 ::1 6082 Rd vcl.load vcl_a072acef-609b-4c25-aa83-00fd713d24d9 /etc/varnish/default.vcl
varnishd[14957]: reloaded country!
varnishd[9899]: CLI telnet ::1 43639 ::1 6082 Wr 200 VCL compiled.
varnishd[9899]: CLI telnet ::1 43642 ::1 6082 Rd auth 5b845ad4f98dbbff0966676713df09e21c75197673b1ca914eb45496985c68e8
varnishd[9899]: CLI telnet ::1 43642 ::1 6082 Wr 200 -----------------------------#012Varnish Cache CLI 1.0#012-----------------------------#012Linux,3.16.0-4-amd64,x86_64,-junix,-smalloc,-smalloc,-hcritbit#012varnish-5.1.3 revision 05c5ac6b9#012#012Type 'help' for command list.#012Type 'quit' to close CLI session.
varnishd[9899]: CLI telnet ::1 43642 ::1 6082 Rd ping
varnishd[9899]: CLI telnet ::1 43642 ::1 6082 Wr 200 PONG 1504722403 1.0
varnishd[9899]: CLI telnet ::1 43642 ::1 6082 Rd vcl.use vcl_a072acef-609b-4c25-aa83-00fd713d24d9
varnishd[9899]: CLI telnet ::1 43642 ::1 6082 Wr 200 VCL 'vcl_a072acef-609b-4c25-aa83-00fd713d24d9' now active
reload-vcl[16112]: VCL compiled.
reload-vcl[16112]: VCL 'vcl_a072acef-609b-4c25-aa83-00fd713d24d9' now active
reload-vcl[16112]: VCL reloaded, active label is vcl_a072acef-609b-4c25-aa83-00fd713d24d9
systemd[1]: Reloaded Varnish HTTP accelerator.
```

**Comment by dbsdsun** [comment]
I don't use  "service varnish reload"
What I did is:
    1. update the Maxmind database
    2. reload vcl with a new name
    3. use the new vcl

**Comment by dugwood** [comment]
OK, so it's about the same as `varnish_reload_vcl`. Do you use `varnishadm` to reload it?

**Comment by dvershinin** [comment]
Hi @fgsch,

Please take note about this [thread](https://varnish-cache.org/lists/pipermail/varnish-misc/2018-August/026451.html). 

To recap: memory gradually increases with every VCL reload, which means a certain increase in memory usage weekly (or as often as GeoIP databases are updated).

This issue can be circumvented with the new `varnishreload` script in Varnish 6.0, but 4.x branch has nothing like it. (Or at least nothing as easy as that).

So it would be nice for the VMOD to periodically (e.g. once in a day) check if database file's modification time has changed and reopen it. Instead of actual VCL reload.

For example, the [GeoIP 2 nginx module](https://github.com/leev/ngx_http_geoip2_module) implements database reload with a configurable setting: `auto_reload <interval>`. 

Would it be possible to implement the same? Thus avoiding the potential memory increase.

**Comment by fgsch** [comment]
@dvershinin I don't have plans to implement this feature.
This is a limitation in the version of varnish you are using and is outside this particular vmod; any changes in your VCL and/or data used by it or any modules will have the same problems. 
Adding extra code to handle it, which is fixed in newer versions, is not the right approach IMO, sorry.
